# Generated by Django 6.0.7 on 2026-08-02 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(db_index=True, max_length=3)),
                ('to_currency', models.CharField(db_index=True, max_length=3)),
                ('from_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('to_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conversion histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
